version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
